/*
 * Copyright 2022 Javier Llorente <javier@opensuse.org>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.javierllorente.netbeans.rest.client.ui;

import java.awt.CardLayout;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Javier Llorente <javier@opensuse.org>
 */
public class AuthPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthPanel
     */
    public AuthPanel() {
        initComponents();
    }
    
    public String getAuthType() {
        return authComboBox.getSelectedItem().toString();
    }
    
    public void setAuthType(String type) {
        authComboBox.setSelectedItem(type);
    }
    
    public String getUsername() {
        return usernameTextField.getText();
    }
    
    public void setUsername(String username) {
        usernameTextField.setText(username);
    }
    
    public String getPassword() {
        return String.valueOf(passwordField.getPassword());
    }
    
    public void setToken(String token) {
        tokenTextField.setText(token);
    }
    
    public void addTokenDocumentListener(DocumentListener dl) {
        tokenTextField.getDocument().addDocumentListener(dl);
    }
    
    public void removeTokenDocumentListener(DocumentListener dl) {
        tokenTextField.getDocument().removeDocumentListener(dl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authComboBox = new javax.swing.JComboBox<>();
        authTypePanel = new javax.swing.JPanel();
        noAuthPanel = new javax.swing.JPanel();
        bearerTokenPanel = new javax.swing.JPanel();
        tokenLabel = new javax.swing.JLabel();
        tokenTextField = new javax.swing.JTextField();
        basicAuthPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(800, 144));

        authComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Auth", "Bearer Token", "Basic Auth" }));
        authComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authComboBoxActionPerformed(evt);
            }
        });

        authTypePanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout noAuthPanelLayout = new javax.swing.GroupLayout(noAuthPanel);
        noAuthPanel.setLayout(noAuthPanelLayout);
        noAuthPanelLayout.setHorizontalGroup(
            noAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        noAuthPanelLayout.setVerticalGroup(
            noAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        authTypePanel.add(noAuthPanel, "No Auth");

        org.openide.awt.Mnemonics.setLocalizedText(tokenLabel, "Token:");

        javax.swing.GroupLayout bearerTokenPanelLayout = new javax.swing.GroupLayout(bearerTokenPanel);
        bearerTokenPanel.setLayout(bearerTokenPanelLayout);
        bearerTokenPanelLayout.setHorizontalGroup(
            bearerTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bearerTokenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tokenLabel)
                .addGap(18, 18, 18)
                .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        bearerTokenPanelLayout.setVerticalGroup(
            bearerTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bearerTokenPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bearerTokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tokenLabel)
                    .addComponent(tokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        authTypePanel.add(bearerTokenPanel, "Bearer Token");

        org.openide.awt.Mnemonics.setLocalizedText(usernameLabel, "Username:");

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, "Password:");

        javax.swing.GroupLayout basicAuthPanelLayout = new javax.swing.GroupLayout(basicAuthPanel);
        basicAuthPanel.setLayout(basicAuthPanelLayout);
        basicAuthPanelLayout.setHorizontalGroup(
            basicAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicAuthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(basicAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        basicAuthPanelLayout.setVerticalGroup(
            basicAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicAuthPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(basicAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basicAuthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        authTypePanel.add(basicAuthPanel, "Basic Auth");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(authTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(authTypePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void authComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authComboBoxActionPerformed
        CardLayout cardLayout = (CardLayout) authTypePanel.getLayout();
        cardLayout.show(authTypePanel, authComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_authComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> authComboBox;
    private javax.swing.JPanel authTypePanel;
    private javax.swing.JPanel basicAuthPanel;
    private javax.swing.JPanel bearerTokenPanel;
    private javax.swing.JPanel noAuthPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel tokenLabel;
    private javax.swing.JTextField tokenTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
